version: '3'

services:
  sfwebapi:
    image: sfwebapi:dev
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_sfwebapi$
    volumes:
      - C:\Users\Srikantansurface\source\repos\sfwebapi\sfwebapi:/app
      - C:\Users\Srikantansurface\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_sfwebapi$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_sfwebapi$ bin/Debug/netcoreapp2.0/sfwebapi.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""
